name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - "charts/**"

permissions: read-all

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      # if we deice to push the chart to ghcr.io as well, uncomment the following:
      # packages: write
    steps:
      - name: Add workspace as safe directory
        run: |
          git config --global --add safe.directory /__w/hapi-fhir-jpaserver-starter/hapi-fhir-jpaserver-starter

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Update dependencies
        run: find charts/ ! -path charts/ -maxdepth 1 -type d -exec helm dependency update {} \;

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@be16258da8010256c6e82849661221415f031968 # v1.5.0
        with:
          config: .github/ct/config.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
