---
name: Lint Code Base
#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#
on:
  push:
    # run on pushes to master
    branches: [master]
  pull_request:
    # and on PRs against master
    branches: [master]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          # Will parse the entire repository and find all files to validate across all types.
          # NOTE: When set to false, only new or edited files will be parsed for validation.
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
